### PR TITLE
remove that weird contribution we got

### PR DESCRIPTION
**Pull request by da-kami**

### CODE REVIEW

**Review by bonomat — APPROVED** [review]

**Comment by thomaseizinger** [comment]
We delete it? Can we not just retract it or something, mark it as rejected, I don't know :D

**Comment by thomaseizinger** [comment]
Ping @da-kami:

> We delete it? Can we not just retract it or something, mark it as rejected, I don't know :D

**Comment by da-kami** [comment]
> We delete it? Can we not just retract it or something, mark it as rejected, I don't know :D

Hahaha, yeah, we can keep it and mark it as rejected. I like the idea. OK with that @bonomat ?

**Comment by bonomat** [comment]
sure, happy to keep it ;)

**Comment by da-kami** [comment]
Changed it to be rejected in Readme and top of spike. Like now @thomaseizinger ?

**Review by thomaseizinger — APPROVED** [review]

**Pull request merged**
